### PR TITLE
Fixed SET_SECTOR_TEXTURE fade params, not working propely as documentation says.

### PR DESCRIPTION
**Pull request by CicTec**

### CODE REVIEW

**Comment by MikeDX** [comment]
This seems to change the way set_sector_texture works as it no longer inverts the last parameter (15-n)

**Comment by CicTec** [comment]
Yes, its true, i commit a new code.

**Comment by MikeDX** [comment]
This still seems incorrect. The values should be 0-15 not -1 to 15, hence why the original code states %16 to limit the range from 0-15

**Comment by CicTec** [comment]
Now is fixed

**Comment by MikeDX** [comment]
Not sure why -1 is still being accepted as a value an then not being used. Can you explain?

**Comment by CicTec** [comment]
The DOC says;
"Luminosity of the texture. from 0 (ambience colour, which is normally black) up to 15 (texture with the original colours).
If a -1 is indicated, the current level of luminosity in the sector will remain unchanged"

So if we have:
set_sector_texture(R, F, C, 12);
set_sector_texture(R, F, C, -1);

The value should be still on 12 (last correct call), instead is resetted to 15 using -1, now still on 12.

**Pull request merged**
