### PR TITLE
Fix null pointer dereference, clean up draw_o.c a bit

### PR DESCRIPTION
**Pull request by jonvaldes**
Ok, this one's a bit more "controversial". 

The null pointer problem is 100% legitimate, but about the other cleanups I did afterwards, we can discuss whether they're a good idea or not. I believe the automatic formatting with clang-format is a huge time saver, and I personally hate the upfront declaration of all variables in old C. But if you think otherwise on any of those two things, I'll just leave the nullptr fix in its own pull request and that's it :)

### CODE REVIEW

**Comment by MikeDX** [comment]
Assuming the pic==NULL means the texture is null and cant be drawn, I assume that means the object can't too, so I think that's OK (assuming I understand the function correctly)

as for the formatting and translation, it looks nicer.

However, travis doesn't like that because of the c99 for(int....) declaration so it's the time to decide if that is the way forward or not.

**Comment by jonvaldes** [comment]
Ok, I'll change the for loop to have the variable defined outside for the time being

**Comment by CicTec** [comment]
Hello jonvaldes,

Thanks for the file, but I have already taken delivery of refactoring mode8, then at least for now, as long as this is not done, should not touch other files please, at least to avoid problems.

**Comment by jonvaldes** [comment]
@CicTec cool, I didn't know you were working on that! Ok, I'll shelve this and start cleaning something else. 
Is there any section of the code that's particularly unattended now?

**Comment by CicTec** [comment]
@jonvaldes, no problem. :)

Except the code section for the mode8 (as indicated, I am in charge of ractoring) , and the compiler + interpreter (there is a plan in progress to rewriting to allow new features and avoid loads of problems caused for the current code-base), you can watch any other section of the code (IDE included mode8 editor and run-time library).

I think at the moment the best options are to clean the code (refactoring + bugfix) of what you can and then add new features.

**Pull request closed without merging**
