### PR TITLE
Convert codebase from CP850 charset to UTF8

### PR DESCRIPTION
**Pull request by jonvaldes**
Years ago, computers in Spain used the CP850 charset instead of UTF8, which is what was making ASCII art in source code be displayed as weird characters. Also, spanish characters like ñ á é í ó ú ü now are displayed correctly

### CODE REVIEW

**Comment by MikeDX** [comment]
Wow this is actually huge.

In all my years of working with DIV (since 2000) I had never even realised those comment lines should have been actual lines and not variants of the A character.

I shall just do some final sanity checks on this tomorrow and quite likely merge this request in.

Thanks Jon!

**Comment by jonvaldes** [comment]
I've been trying to convert a few remaining files in the runtime dir, but they seem to have gone through another conversion (probably inadvertently) and I can't get them to display correctly with any encoding.
I guess those will have to be done manually.

**Comment by MikeDX** [comment]
That's almost guaranteed to be my fault as I would have overwritten something accidentally when shuffling things about.

It might be worth going back through the old commits and seeing what the characters used to be. The only useful part of doing that however is to ensure things like the tolower[] char array doesnt break anything.

Did the help file suffer a similar fate?

**Comment by jonvaldes** [comment]
After thinking a bit about it, I guess DIV itself will continue to work in its original charset, so anything that's actually compiled (not just comments) should be left in its original encoding to avoid causing any issues.

Unless of course there was already some problem with displaying characters like ñ, ç or á in DIV DX?

**Comment by MikeDX** [comment]
Due to the way DIV was ported (dirty hacks everywhere to get a result) I was a little bit naughty and "skipped" any internationalisation issues by just changing chars where I needed to in order to get the compiler / runtime to work - sometimes this meant replacing chars. 

I don't believe actual "inputted" special characters in DIV have issues displaying but I do know some users have issues with keyboard input in the editor with certain chars (different issue)

**Pull request merged**
